---
name: Build Python wheels and sdist for NVTX

'on':
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Build sdist
        run: pipx run build --sdist python

      # Ideally, the below step wouldn't be needed, but without it, the
      # installation fails due to a bug in the default setuptools in the
      # ubuntu-latest image. https://github.com/pypa/setuptools/issues/3269
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '>=3.9'

      - name: Install Python NVTX from sdist
        run: pip install python/dist/$(ls python/dist)[test]

      - name: Test sdist
        run: |
          pip install numpy
          pytest python/tests
          pytest --enable-injection python/tests
          pip uninstall -y numpy
          pytest python/tests
          pytest --enable-injection python/tests

      - name: Upload distribution
        uses: actions/upload-artifact@v7
        with:
          name: nvtx-sdist
          path: python/dist

  wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Set up QEMU
        if: matrix.os == 'ubuntu-latest'
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8
        with:
          platforms: arm64

      - name: Build wheels
        uses: pypa/cibuildwheel@1828c10ab37f080699c7b81cea34097c684a7074
        with:
          output-dir: dist
          package-dir: python

      - name: Upload distributions
        uses: actions/upload-artifact@v7
        with:
          path: dist
          name: nvtx-wheels-${{ matrix.os }}
