---
name: Python

'on':
  push:
    paths:
      - .github/workflows/python.yml
      - c/include/**
      - python/*.cfg
      - python/*.in
      - python/*.py
      - python/*.toml
      - python/src/**
      - python/tests/**
  pull_request:
    paths:
      - .github/workflows/python.yml
      - c/include/**
      - python/*.cfg
      - python/*.in
      - python/*.py
      - python/*.toml
      - python/src/**
      - python/tests/**

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-python
  cancel-in-progress: true

jobs:
  pytest:
    name: Test
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, windows-latest, macos-latest]
        pyver: ['3.9', '3.10', '3.11', '3.12', '3.13', 3.13t, '3.14', 3.14t]
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.pyver }}
      - run: pipx run build --sdist python
      - run: pip install ./python[test] numpy
      - run: pytest python/tests
      - run: pytest --enable-injection python/tests
      - run: pip uninstall -y numpy
      - run: pytest python/tests
      - run: pytest --enable-injection python/tests
