name: Rust

on:
  push:
    branches:
      - dev
      - release-v3
      - test-*
    paths:
      - ".github/workflows/rust.yml"
      - "**/Cargo.*"
      - "c/include/**"
      - "rust/crates/**"
      - "rust/examples/**"
      - "rust/src/**"
    tags:
      - "v*"
  pull_request:
    paths:
      - ".github/workflows/rust.yml"
      - "**/Cargo.*"
      - "c/include/**"
      - "rust/crates/**"
      - "rust/examples/**"
      - "rust/src/**"

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-rust
  cancel-in-progress: true

defaults:
  run:
    working-directory: rust

env:
  CARGO_CACHE_PATH: |
    ~/.cargo/bin/
    ~/.cargo/registry/index/
    ~/.cargo/registry/cache/
    ~/.cargo/git/db/
    target/

jobs:
  msrv:
    name: Minimum supported Rust version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v5
        with:
          path: ${{ env.CARGO_CACHE_PATH }}
          key: ${{ runner.os }}-cargo-${{ steps.toolchain.outputs.cachekey }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-${{ steps.toolchain.outputs.cachekey }}-
      - run: rustup install 1.77.0
      - run: cargo +1.77.0 check --workspace --all-targets --all-features

  deny:
    name: Deny
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v5
        with:
          path: ${{ env.CARGO_CACHE_PATH }}
          key: ${{ runner.os }}-cargo-deny-${{ steps.toolchain.outputs.cachekey }}
          restore-keys: ${{ runner.os }}-cargo-deny-
      - run: cargo install --locked cargo-deny || true
      - run: cargo deny --workspace --all-features check --show-stats

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: cargo fmt --all -- --check

  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        features: ["--all-features", "--no-default-features"]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v5
        with:
          path: ${{ env.CARGO_CACHE_PATH }}
          key: ${{ runner.os }}-cargo-check-${{ steps.toolchain.outputs.cachekey }}-${{ matrix.features }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-check-${{ steps.toolchain.outputs.cachekey }}-${{ matrix.features }}-
      - name: Check
        run: cargo check --workspace --all-targets ${{ matrix.features }}
      - name: Clippy
        run: cargo clippy --workspace --all-targets ${{ matrix.features }} -- -Dwarnings
      - name: Test
        run: cargo test --workspace --all-targets ${{ matrix.features }}
      - name: Doctest
        run: cargo test --workspace --doc ${{ matrix.features }}
